In [17]:
from students_matching import StudentsMatching
import random
import warnings
warnings.filterwarnings("ignore")

In [89]:
num_students = 450
num_profiles = 8

min_num_groups = [0, 0, 0, 0, 0, 0, 0, 0]
max_num_groups = [2, 2, 4, 2, 9, 3, 3, 4]
max_group_sizes = [20, 25, 30, 32, 27, 30, 20, 30]
min_group_sizes = [18, 18, 27, 30, 25, 30, 15, 30]

perc_of_target = 0.05
perc_of_contract = 0.3
debts_limit = 5
first_pref = 55
first_pref_target = 5

In [90]:
matching = StudentsMatching(num_students, num_profiles, perc_of_target,
                            perc_of_contract, debts_limit, first_pref, first_pref_target,
                            min_num_groups, max_num_groups, min_group_sizes, max_group_sizes)

In [91]:
for prof in matching.data_p.index:
    print(f"Профиль {prof}: Студенты, поставившие первым приоритетом: {matching.priorities[prof]}, "
          f"целевиков: {matching.priorities_target[prof]}")

print(f"Размер резерва студентов: {matching.reserve_size}")
print(f"Резерв студентов: {matching.reserve_students}")

Профиль 0: Студенты, поставившие первым приоритетом: 45, целевиков: 4
Профиль 1: Студенты, поставившие первым приоритетом: 51, целевиков: 4
Профиль 2: Студенты, поставившие первым приоритетом: 71, целевиков: 3
Профиль 3: Студенты, поставившие первым приоритетом: 47, целевиков: 2
Профиль 4: Студенты, поставившие первым приоритетом: 44, целевиков: 2
Профиль 5: Студенты, поставившие первым приоритетом: 48, целевиков: 2
Профиль 6: Студенты, поставившие первым приоритетом: 47, целевиков: 1
Профиль 7: Студенты, поставившие первым приоритетом: 62, целевиков: 4
Размер резерва студентов: 57
Резерв студентов: [44, 428, 236, 248, 256, 32, 3, 147, 85, 204, 345, 387, 219, 33, 113, 46, 363, 202, 70, 316, 392, 325, 221, 296, 233, 262, 421, 386, 154, 291, 173, 149, 440, 208, 57, 33, 113, 46, 363, 202, 70, 316, 392, 325, 221, 296, 233, 262, 421, 386, 154, 291, 173, 149, 440, 208, 57]

In [92]:
matching.gale_shapley(matching.sorted_students)
for prof, matched_students in matching.profiles_matches.items():
    print(f"Профиль {prof}: Студенты - {matched_students}")
    print(f"Всего на профиле {prof} {len(matched_students)} студентов")

    max_size = matching.data_p.loc[prof, 'max_group_size']
    min_size = matching.data_p.loc[prof, 'min_group_size']
    if len(matched_students) > 0:
        full_groups = len(matched_students) // max_size
        small_groups = len(matched_students) // min_size
        if len(matched_students) % max_size == 0:
            print(f"На профиле {prof} можно сформировать {full_groups} полных групп.")
        elif small_groups == full_groups:
            students_to_remove = len(matched_students) % max_size
            students_to_add = min_size - len(matched_students) % min_size
            print(f"Для максимальной заполненности {full_groups} групп профиля {prof} выгнать: {students_to_remove}")
            print(f"Для минимальной заполненности {small_groups + 1} групп профиля {prof} добавить: {students_to_add}")
        else:
            print(f"Студентов профиля {prof} можно распределить в {small_groups} групп")
            students_needed_to_max = max_size - len(matched_students) % max_size 
            print(f"Не хватает студентов до максимальной заполненности групп для профиля {prof}: {students_needed_to_max}")
    else:
        print(f"На профиле {prof} нет зачисленных студентов.")

Профиль 0: Студенты - [303, 181, 356, 142, 176, 305, 298, 439, 396, 228, 297, 286, 273, 77, 30, 26, 14, 193, 381, 203, 269, 229, 123, 309, 313, 114, 285, 8, 110, 143, 417, 321, 274, 333, 394, 86, 278, 441, 340, 172]
Всего на профиле 0 40 студентов
На профиле 0 можно сформировать 2 полных групп.
Профиль 1: Студенты - [158, 254, 259, 247, 416, 199, 19, 447, 96, 60, 20, 182, 183, 234, 367, 318, 168, 448, 17, 187, 432, 413, 241, 196, 377, 335, 265, 47, 232, 212, 320, 258, 166, 198, 61, 71, 295, 361, 344, 41, 205, 68, 81, 88, 201, 105, 217, 174, 255, 449]
Всего на профиле 1 50 студентов
На профиле 1 можно сформировать 2 полных групп.
Профиль 2: Студенты - [288, 244, 90, 188, 169, 165, 102, 125, 66, 63, 249, 222, 343, 131, 330, 139, 216, 132, 145, 332, 434, 404, 43, 284, 306, 35, 326, 290, 144, 118, 180, 194, 83, 272, 371, 338, 67, 324, 260, 348, 336, 289, 385, 263, 94, 130, 423, 51, 29, 266, 150, 314, 31, 163, 224, 398, 138, 419, 391, 13, 184, 327, 337, 99, 433, 164, 146, 271, 115, 378, 270]
Всего на профиле 2 71 студентов
Для максимальной заполненности 2 групп профиля 2 выгнать: 11
Для минимальной заполненности 3 групп профиля 2 добавить: 10
Профиль 3: Студенты - [365, 281, 283, 135, 128, 107, 75, 376, 370, 109, 251, 11, 422, 427, 127, 374, 179, 22, 62, 28, 197, 215, 443, 82, 354, 7, 50, 155, 282, 329, 397, 59, 438, 424, 430, 223, 437, 403, 414, 93, 84, 445, 429, 292, 317, 0, 319, 353, 200]
Всего на профиле 3 49 студентов
Для максимальной заполненности 1 групп профиля 3 выгнать: 17
Для минимальной заполненности 2 групп профиля 3 добавить: 11
Профиль 4: Студенты - [231, 218, 101, 261, 192, 134, 352, 389, 339, 277, 399, 225, 191, 100, 69, 6, 362, 178, 12, 42, 436, 237, 388, 214, 226, 97, 171, 293, 78, 108, 301, 213, 382, 342, 141, 347, 91, 431, 402, 446, 207, 136, 246, 355]
Всего на профиле 4 44 студентов
Для максимальной заполненности 1 групп профиля 4 выгнать: 17
Для минимальной заполненности 2 групп профиля 4 добавить: 6
Профиль 5: Студенты - [152, 52, 116, 95, 39, 435, 185, 190, 170, 48, 341, 235, 405, 383, 240, 250, 124, 55, 299, 206, 384, 25, 167, 1, 328, 117, 268, 80, 358, 129, 34, 148, 411, 49, 38, 161, 412, 442, 153, 27, 375, 351, 10, 238, 418, 21, 220, 331, 103, 243]
Всего на профиле 5 50 студентов
Для максимальной заполненности 1 групп профиля 5 выгнать: 20
Для минимальной заполненности 2 групп профиля 5 добавить: 10
Профиль 6: Студенты - [156, 304, 311, 137, 18, 92, 253, 275, 16, 76, 364, 89, 133, 315, 227, 369, 37, 359, 45, 239, 5, 373, 126, 395, 4, 420, 444, 73, 390, 350, 210, 400, 408, 36, 15, 53, 360, 308, 323, 393, 40, 334, 140, 307, 64, 54, 112, 415, 157]
Всего на профиле 6 49 студентов
Студентов профиля 6 можно распределить в 3 групп
Не хватает студентов до максимальной заполненности групп для профиля 6: 11
Профиль 7: Студенты - [252, 160, 410, 349, 257, 280, 58, 72, 302, 122, 346, 368, 245, 211, 425, 312, 279, 74, 195, 209, 372, 162, 230, 121, 111, 65, 366, 267, 276, 380, 189, 119, 79, 406, 120, 409, 56, 23, 104, 401, 175, 98, 294, 264, 322, 106, 2, 357, 242, 287, 177, 24, 151, 159, 379, 87, 407, 426, 310, 300, 186, 9]
Всего на профиле 7 62 студентов
Для максимальной заполненности 2 групп профиля 7 выгнать: 2
Для минимальной заполненности 3 групп профиля 7 добавить: 28

In [93]:
print("Незачисленные студенты:")
print(matching.unmatched_students)

Незачисленные студенты:
[3, 32, 33, 44, 46, 57, 70, 85, 113, 147, 149, 154, 173, 202, 204, 208, 219, 221, 233, 236, 248, 256, 262, 291, 296, 316, 325, 345, 363, 386, 387, 392, 421, 428, 440]

In [94]:
matching.calculate_prof_status()
matching.prof_status

[1, 1, 0, 0, 0, 0, 1, 0]

In [95]:
matching.a

30

In [96]:
matching.preparing_for_redistribution()

есть лишние студенты
студенты к распределению: [200, 243, 103, 331, 270, 378, 157, 355, 246, 353, 115, 220, 21, 136, 415, 9, 319, 449, 418, 112, 207, 255, 446, 174, 271, 186, 3, 32, 33, 44, 46, 57, 70, 85, 113, 147, 149, 154, 173, 202, 204, 208, 219, 221, 233, 236, 248, 256, 262, 291, 296, 316, 325, 345, 363, 386, 387, 392, 421, 428, 440]

In [97]:
matching.data_p

,min_num_groups,max_num_groups,min_group_size,max_group_size,quota,preferences
0,0,2,18,20,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
1,0,2,18,25,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
2,1,4,27,30,14,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
3,0,2,30,32,14,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
4,0,9,25,27,11,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
5,0,3,30,30,16,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
6,0,3,15,20,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
7,1,4,30,30,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."

In [98]:
matching.gale_shapley_redistribution(matching.free_st)
for prof, matched_students in matching.profiles_matches.items():
    print(f"Профиль {prof}: Студенты - {matched_students}")
    print(f"Всего на профиле {prof} {len(matched_students)} студентов")

    max_size = matching.data_p.loc[prof, 'max_group_size']
    min_size = matching.data_p.loc[prof, 'min_group_size']
    if len(matched_students) > 0:
        full_groups = len(matched_students) // max_size
        small_groups = len(matched_students) // min_size
        if len(matched_students) % max_size == 0:
            print(f"На профиле {prof} можно сформировать {full_groups} полных групп.")
            # Обновляем квоту
            matching.data_p.loc[prof, 'quota'] = 0
        elif small_groups == full_groups:
            students_to_remove = len(matched_students) % max_size
            students_to_add = min_size - len(matched_students) % min_size
            # Обновляем квоту
            matching.data_p.loc[prof, 'quota'] = students_to_add
            print(f"Для максимальной заполненности {full_groups} групп профиля {prof} выгнать: {students_to_remove}")
            print(f"Для минимальной заполненности {small_groups + 1} групп профиля {prof} добавить: {students_to_add}")
        else:
            print(f"Студентов профиля {prof} можно распределить в {small_groups} групп")
            students_needed_to_max = max_size - len(matched_students) % max_size 
            matching.data_p.loc[prof, 'quota'] = students_needed_to_max
            # Обновляем квоту
            matching.data_p.loc[prof, 'quota'] = 0
            print(f"Не хватает студентов до максимальной заполненности групп для профиля {prof}: {students_needed_to_max}")
    else:
        print(f"На профиле {prof} нет зачисленных студентов.")

Профиль 0: Студенты - [303, 181, 356, 142, 176, 305, 298, 439, 396, 228, 297, 286, 273, 77, 30, 26, 14, 193, 381, 203, 269, 229, 123, 309, 313, 114, 285, 8, 110, 143, 417, 321, 274, 333, 394, 86, 278, 441, 340, 172]
Всего на профиле 0 40 студентов
На профиле 0 можно сформировать 2 полных групп.
Профиль 1: Студенты - [158, 254, 259, 247, 416, 199, 19, 447, 96, 60, 20, 182, 183, 234, 367, 318, 168, 448, 17, 187, 432, 413, 241, 196, 377, 335, 265, 47, 232, 212, 320, 258, 166, 198, 61, 71, 295, 361, 344, 41, 205, 68, 81, 88, 201, 105, 217]
Всего на профиле 1 47 студентов
Студентов профиля 1 можно распределить в 2 групп
Не хватает студентов до максимальной заполненности групп для профиля 1: 3
Профиль 2: Студенты - [288, 244, 90, 188, 169, 165, 102, 125, 66, 63, 249, 222, 343, 131, 330, 139, 216, 132, 145, 332, 434, 404, 43, 284, 306, 35, 326, 290, 144, 118, 180, 194, 83, 272, 371, 338, 67, 324, 260, 348, 336, 289, 385, 263, 94, 130, 423, 51, 29, 266, 150, 314, 31, 163, 224, 398, 138, 419, 391, 13, 184, 327, 337, 99, 433, 164, 146, 270, 378, 115, 415, 271]
Всего на профиле 2 72 студентов
Для максимальной заполненности 2 групп профиля 2 выгнать: 12
Для минимальной заполненности 3 групп профиля 2 добавить: 9
Профиль 3: Студенты - [365, 281, 283, 135, 128, 107, 75, 376, 370, 109, 251, 11, 422, 427, 127, 374, 179, 22, 62, 28, 197, 215, 443, 82, 354, 7, 50, 155, 282, 329, 397, 59, 438, 424, 430, 223, 437, 403, 414, 93, 84, 445, 429, 292, 317, 0, 200, 353, 319, 449, 186]
Всего на профиле 3 51 студентов
Для максимальной заполненности 1 групп профиля 3 выгнать: 19
Для минимальной заполненности 2 групп профиля 3 добавить: 9
Профиль 4: Студенты - [231, 218, 101, 261, 192, 134, 352, 389, 339, 277, 399, 225, 191, 100, 69, 6, 362, 178, 12, 42, 436, 237, 388, 214, 226, 97, 171, 293, 78, 108, 301, 213, 382, 342, 141, 347, 91, 431, 402, 355, 246, 136, 9, 112, 207, 255, 446, 174]
Всего на профиле 4 48 студентов
Для максимальной заполненности 1 групп профиля 4 выгнать: 21
Для минимальной заполненности 2 групп профиля 4 добавить: 2
Профиль 5: Студенты - [152, 52, 116, 95, 39, 435, 185, 190, 170, 48, 341, 235, 405, 383, 240, 250, 124, 55, 299, 206, 384, 25, 167, 1, 328, 117, 268, 80, 358, 129, 34, 148, 411, 49, 38, 161, 412, 442, 153, 27, 375, 351, 10, 238, 243, 103, 331, 157, 220, 21, 418]
Всего на профиле 5 51 студентов
Для максимальной заполненности 1 групп профиля 5 выгнать: 21
Для минимальной заполненности 2 групп профиля 5 добавить: 9
Профиль 6: Студенты - [156, 304, 311, 137, 18, 92, 253, 275, 16, 76, 364, 89, 133, 315, 227, 369, 37, 359, 45, 239, 5, 373, 126, 395, 4, 420, 444, 73, 390, 350, 210, 400, 408, 36, 15, 53, 360, 308, 323, 393, 40, 334, 140, 307, 64, 54]
Всего на профиле 6 46 студентов
Студентов профиля 6 можно распределить в 3 групп
Не хватает студентов до максимальной заполненности групп для профиля 6: 14
Профиль 7: Студенты - [252, 160, 410, 349, 257, 280, 58, 72, 302, 122, 346, 368, 245, 211, 425, 312, 279, 74, 195, 209, 372, 162, 230, 121, 111, 65, 366, 267, 276, 380, 189, 119, 79, 406, 120, 409, 56, 23, 104, 401, 175, 98, 294, 264, 322, 106, 2, 357, 242, 287, 177, 24, 151, 159, 379, 87, 407, 426, 310, 300]
Всего на профиле 7 60 студентов
На профиле 7 можно сформировать 2 полных групп.

In [99]:
matching.data_p

,min_num_groups,max_num_groups,min_group_size,max_group_size,quota,preferences
0,0,2,18,20,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
1,0,2,18,25,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
2,1,4,27,30,9,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
3,0,2,30,32,9,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
4,0,9,25,27,2,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
5,0,3,30,30,9,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
6,0,3,15,20,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."
7,1,4,30,30,0,"[288, 303, 244, 156, 365, 152, 181, 356, 252, ..."

In [100]:
print("Незачисленные студенты:")
print(matching.unmatched_students)

Незачисленные студенты:
[3, 32, 33, 44, 46, 57, 70, 85, 113, 147, 149, 154, 173, 202, 204, 208, 219, 221, 233, 236, 248, 256, 262, 291, 296, 316, 325, 345, 363, 386, 387, 392, 421, 428, 440]

In [101]:
matching.random_distribution()

In [102]:
for prof, matched_students in matching.profiles_matches.items():
    print(f"Профиль {prof}: Студенты - {matched_students}")
    print(f"Всего на профиле {prof} {len(matched_students)} студентов")

    max_size = matching.data_p.loc[prof, 'max_group_size']
    min_size = matching.data_p.loc[prof, 'min_group_size']
    if len(matched_students) > 0:
        full_groups = len(matched_students) // max_size
        small_groups = len(matched_students) // min_size
        if len(matched_students) % max_size == 0:
            print(f"На профиле {prof} можно сформировать {full_groups} полных групп.")
        elif small_groups == full_groups:
            students_to_remove = len(matched_students) % max_size
            students_to_add = min_size - len(matched_students) % min_size
            print(f"Для максимальной заполненности {full_groups} групп профиля {prof} выгнать: {students_to_remove}")
            print(f"Для минимальной заполненности {small_groups + 1} групп профиля {prof} добавить: {students_to_add}")
        else:
            print(f"Студентов профиля {prof} можно распределить в {small_groups} групп")
            students_needed_to_max = max_size - len(matched_students) % max_size
            print(f"Не хватает студентов до максимальной заполненности групп для профиля {prof}: {students_needed_to_max}")
    else:
        print(f"На профиле {prof} нет зачисленных студентов.")

Профиль 0: Студенты - [303, 181, 356, 142, 176, 305, 298, 439, 396, 228, 297, 286, 273, 77, 30, 26, 14, 193, 381, 203, 269, 229, 123, 309, 313, 114, 285, 8, 110, 143, 417, 321, 274, 333, 394, 86, 278, 441, 340, 172]
Всего на профиле 0 40 студентов
На профиле 0 можно сформировать 2 полных групп.
Профиль 1: Студенты - [158, 254, 259, 247, 416, 199, 19, 447, 96, 60, 20, 182, 183, 234, 367, 318, 168, 448, 17, 187, 432, 413, 241, 196, 377, 335, 265, 47, 232, 212, 320, 258, 166, 198, 61, 71, 295, 361, 344, 41, 205, 68, 81, 88, 201, 105, 217]
Всего на профиле 1 47 студентов
Студентов профиля 1 можно распределить в 2 групп
Не хватает студентов до максимальной заполненности групп для профиля 1: 3
Профиль 2: Студенты - [288, 244, 90, 188, 169, 165, 102, 125, 66, 63, 249, 222, 343, 131, 330, 139, 216, 132, 145, 332, 434, 404, 43, 284, 306, 35, 326, 290, 144, 118, 180, 194, 83, 272, 371, 338, 67, 324, 260, 348, 336, 289, 385, 263, 94, 130, 423, 51, 29, 266, 150, 314, 31, 163, 224, 398, 138, 419, 391, 13, 184, 327, 337, 99, 433, 164, 146, 270, 378, 115, 415, 271, 33, 70, 147, 149, 173, 204, 236, 262, 291]
Всего на профиле 2 81 студентов
Студентов профиля 2 можно распределить в 3 групп
Не хватает студентов до максимальной заполненности групп для профиля 2: 9
Профиль 3: Студенты - [365, 281, 283, 135, 128, 107, 75, 376, 370, 109, 251, 11, 422, 427, 127, 374, 179, 22, 62, 28, 197, 215, 443, 82, 354, 7, 50, 155, 282, 329, 397, 59, 438, 424, 430, 223, 437, 403, 414, 93, 84, 445, 429, 292, 317, 0, 200, 353, 319, 449, 186, 3, 57, 154, 221, 233, 316, 325, 345, 363]
Всего на профиле 3 60 студентов
Студентов профиля 3 можно распределить в 2 групп
Не хватает студентов до максимальной заполненности групп для профиля 3: 4
Профиль 4: Студенты - [231, 218, 101, 261, 192, 134, 352, 389, 339, 277, 399, 225, 191, 100, 69, 6, 362, 178, 12, 42, 436, 237, 388, 214, 226, 97, 171, 293, 78, 108, 301, 213, 382, 342, 141, 347, 91, 431, 402, 355, 246, 136, 9, 112, 207, 255, 446, 174, 44, 46]
Всего на профиле 4 50 студентов
Студентов профиля 4 можно распределить в 2 групп
Не хватает студентов до максимальной заполненности групп для профиля 4: 4
Профиль 5: Студенты - [152, 52, 116, 95, 39, 435, 185, 190, 170, 48, 341, 235, 405, 383, 240, 250, 124, 55, 299, 206, 384, 25, 167, 1, 328, 117, 268, 80, 358, 129, 34, 148, 411, 49, 38, 161, 412, 442, 153, 27, 375, 351, 10, 238, 243, 103, 331, 157, 220, 21, 418, 32, 85, 113, 202, 208, 219, 248, 256, 296]
Всего на профиле 5 60 студентов
На профиле 5 можно сформировать 2 полных групп.
Профиль 6: Студенты - [156, 304, 311, 137, 18, 92, 253, 275, 16, 76, 364, 89, 133, 315, 227, 369, 37, 359, 45, 239, 5, 373, 126, 395, 4, 420, 444, 73, 390, 350, 210, 400, 408, 36, 15, 53, 360, 308, 323, 393, 40, 334, 140, 307, 64, 54]
Всего на профиле 6 46 студентов
Студентов профиля 6 можно распределить в 3 групп
Не хватает студентов до максимальной заполненности групп для профиля 6: 14
Профиль 7: Студенты - [252, 160, 410, 349, 257, 280, 58, 72, 302, 122, 346, 368, 245, 211, 425, 312, 279, 74, 195, 209, 372, 162, 230, 121, 111, 65, 366, 267, 276, 380, 189, 119, 79, 406, 120, 409, 56, 23, 104, 401, 175, 98, 294, 264, 322, 106, 2, 357, 242, 287, 177, 24, 151, 159, 379, 87, 407, 426, 310, 300]
Всего на профиле 7 60 студентов
На профиле 7 можно сформировать 2 полных групп.

In [103]:
print("Незачисленные студенты:")
print(matching.unmatched_students)

Незачисленные студенты:
[]